services:
  web:
    build: .docker/dev
    container_name: tripwire_web
    ports: 
      - 8081:80
    networks:
      - web
      - tripwire
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=tripwire_web"

      # Router rule for domain
      - "traefik.http.routers.nginx.rule=Host(`your domain`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certresolver=myresolver"

      # Fallback to plain HTTP -> redirect to HTTPS
      - "traefik.http.routers.nginx_http.rule=Host(`your domain`)"
      - "traefik.http.routers.nginx_http.entrypoints=web"
      - "traefik.http.routers.nginx_http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # Let Traefik know container listens on port 80 internally
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    volumes:
      - "./:/var/www/html/tripwire"
    env_file:
      - .env

  #################################################################
  # OFFICIAL MYSQL 8.0.40 SERVICE
  #################################################################
  mysql:
    image: mysql:8.0.40
    container_name: mysql
    networks:
      - tripwire
    environment:
      - MYSQL_ROOT_PASSWORD=root_password # do not use quotes
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME} # do not use quotes
      - MYSQL_PASSWORD=${DB_PASSWORD} # do not use quotes
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    container_name: adminer
    image: adminer
    networks:
      - tripwire
    ports:
      - 9000:8080
 


volumes:
  mysql-data:

networks:
  web:
  tripwire:
