version: "3"
services:
  nginx:
    build: .docker/nginx
    container_name: nginx
    ports:
      - 8081:80
    networks:
      - web #- Used with Traefik
      - tripwire
    labels:
      - "traefik.frontend.rule=Host:example.com" # Used with Traefik to set your host
      - "traefik.docker.network=web"
      - "traefik.port=80"
      - "traefik.enable=true" # Traefik is not enabled on all services by default
    volumes:
      - "./:/opt/app"
    command: nginx
    env_file:
      - .env


  php-fpm:
    build: .docker/php-fpm
    container_name: php-fpm
    networks:
      - tripwire
    volumes:
      - "./:/opt/app"
    command: php-fpm
    env_file:
      - .env

  mysql:
    # image: percona
    build:
      context: .
      dockerfile: .docker/mysql/Dockerfile
    networks:
      - tripwire
    volumes:
      - mysql-data:/var/lib/mysql
      - ./.docker/mysql/tripwire.sql:/tmp/tripwire.sql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - TRIPWIRE_DATABASE=tripwire
      - SDE_DATABASE=eve_dump
    entrypoint: sh -c "/tmp/init.sh && echo 'starting mysql...' && /docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"

  # Development only - For database administration
  adminer:
    container_name: adminer
    networks:
      - tripwire
    image: adminer
    ports:
      - 9000:8080

volumes:
  mysql-data:

networks:
  tripwire:
  web:
