name: Build Twipwire

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
    pull_requests:
      branches:
        - 'master'

jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install gulp
        run: npm i -g gulp-cli
      - name: install npm dependancies
        run: npm install
      - name: install composer dependanceis
        run: composer install
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with: 
          images: simplyunnamed/tripwire
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-and-push-action@v3
        with:
          context: .
          file: .docker/build/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}